version: "3"

services:
  #======================================================================
  # NATS Server
  #======================================================================
  nats-server:
    image: nats:latest
    networks:
      - curso-nestjs

  #======================================================================
  # CLIENT GATEWAY
  #======================================================================
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    # image: dockerwallas/nestjs-repository:0.0.1
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
    networks:
      - curso-nestjs

  #======================================================================
  # AUTH MICROSERVICE
  #======================================================================
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    environment:
      - NODE_ENV=development
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - curso-nestjs

  #======================================================================
  # PRODUCTS MICROSERVICE
  #======================================================================
  products-ms:
    build:
      context: ./products
      dockerfile: dockerfile.prod
    image: products-ms-prod
    environment:
      - NODE_ENV=development
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./productDb.db
    networks:
      - curso-nestjs
  #======================================================================
  # ORDERS MICROSERVICE
  #======================================================================
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
    image: orders-ms-prod
    environment:
      - NODE_ENV=development
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}
    networks:
      - curso-nestjs

  #======================================================================
  # PAYMENTS MICROSERVICE
  #======================================================================
  payments-ms:
    build:
      context: ./payments
      dockerfile: dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - NODE_ENV=development
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - ENDPOINT_SECRET=${ENDPOINT_SECRET}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}
    networks:
      - curso-nestjs

networks:
  curso-nestjs:
    name: curso-solver-nestjs
