apiVersion: v1
kind: Pod
metadata:
  name: gateway
spec:
  # replicas: 1
  # selector:
  #   matchLabels:
  #     app: gateway
  containers:
    - name: gateway
      image: dockerwallas/nestjs-repository:0.0.3
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: PORT
        - name: NATS_SERVERS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: NATS_SERVERS
